

local Resources = {}

function Resources:load_assets()
  local textures = {
    { key = "sprites",      path = "game/assets/textures/sprites.png" },
    { key = "tiles",        path = "game/assets/textures/tiles.png" },
    { key = "effects",      path = "game/assets/textures/effects.png" },
    { key = "gui",          path = "game/assets/textures/gui.png" },
  }

  local sounds = {
    { key = "fire",         path = "game/assets/sounds/fire.wav" },
  }

  local music = {
    { key = "adagio",       path = "game/assets/music/adagio.wav" },
  }

  local texture_rval = true
  for index, elm in ipairs(textures) do
    texture_rval = texture_rval and resources_load_texture(elm.key, elm.path)
  end
  print("load textures: " .. tostring(texture_rval))

  local sounds_rval = true
  for index, elm in ipairs(sounds) do
    sounds_rval = sounds_rval and resources_load_sound(elm.key, elm.path)
  end
  print("load sounds: " .. tostring(sounds_rval))

  local music_rval = true
  for index, elm in ipairs(music) do
    music_rval = music_rval and resources_load_music(elm.key, elm.path)
  end
  print("load music: " .. tostring(music_rval))

  return texture_rval and sounds_rval and music_rval
end


function Resources:load_font()
  local small_font = {
    key = "small_font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 8,
    spacing = 1,
    letters = {
      { letter = '!',     x = 1,       y = 1,      w = 1 },
      { letter = '"',     x = 3,       y = 1,      w = 3 },
      { letter = '#',     x = 8,       y = 1,      w = 4 },
      { letter = '$',     x = 14,      y = 1,      w = 3 },
      { letter = '%',     x = 19,      y = 1,      w = 5 },
      { letter = '&',     x = 26,      y = 1,      w = 5 },
      { letter = '\'',    x = 32,      y = 1,      w = 1 },
      { letter = '(',     x = 35,      y = 1,      w = 2 },
      { letter = ')',     x = 38,      y = 1,      w = 2 },
      { letter = '*',     x = 42,      y = 1,      w = 3 },
      { letter = '+',     x = 47,      y = 1,      w = 3 },
      { letter = ',',     x = 51,      y = 1,      w = 2 },
      { letter = '-',     x = 54,      y = 1,      w = 2 },
      { letter = '.',     x = 57,      y = 1,      w = 1 },
      { letter = '/',     x = 60,      y = 1,      w = 3 },
      { letter = '1',     x = 65,      y = 1,      w = 3 },
      { letter = '2',     x = 69,      y = 1,      w = 4 },
      { letter = '3',     x = 74,      y = 1,      w = 4 },
      { letter = '4',     x = 79,      y = 1,      w = 4 },
      { letter = '5',     x = 84,      y = 1,      w = 4 },
      { letter = '6',     x = 89,      y = 1,      w = 4 },
      { letter = '7',     x = 94,      y = 1,      w = 3 },
      { letter = '8',     x = 98,      y = 1,      w = 4 },
      { letter = '9',     x = 103,     y = 1,      w = 4 },
      { letter = '0',     x = 108,     y = 1,      w = 4 },
      { letter = ':',     x = 114,     y = 1,      w = 1 },
      { letter = ';',     x = 116,     y = 1,      w = 2 },
      { letter = '<',     x = 120,     y = 1,      w = 3 },
      { letter = '=',     x = 124,     y = 1,      w = 3 },
      { letter = '>',     x = 128,     y = 1,      w = 3 },
      { letter = '?',     x = 132,     y = 1,      w = 4 },
      { letter = '@',     x = 137,     y = 1,      w = 6 },

      { letter = 'A',     x = 1,       y = 12,     w = 4 },
      { letter = 'B',     x = 6,       y = 12,     w = 4 },
      { letter = 'C',     x = 11,      y = 12,     w = 3 },
      { letter = 'D',     x = 15,      y = 12,     w = 4 },
      { letter = 'E',     x = 20,      y = 12,     w = 3 },
      { letter = 'F',     x = 24,      y = 12,     w = 3 },
      { letter = 'G',     x = 28,      y = 12,     w = 4 },
      { letter = 'H',     x = 33,      y = 12,     w = 4 },
      { letter = 'I',     x = 38,      y = 12,     w = 1 },
      { letter = 'J',     x = 40,      y = 12,     w = 4 },
      { letter = 'K',     x = 45,      y = 12,     w = 4 },
      { letter = 'L',     x = 50,      y = 12,     w = 3 },
      { letter = 'M',     x = 54,      y = 12,     w = 5 },
      { letter = 'N',     x = 60,      y = 12,     w = 4 },
      { letter = 'O',     x = 65,      y = 12,     w = 4 },
      { letter = 'P',     x = 70,      y = 12,     w = 4 },
      { letter = 'Q',     x = 75,      y = 12,     w = 5 },
      -- { letter = 'Q',     x = 160,     y = 12,     w = 7,      f = 5 },
      { letter = 'R',     x = 81,      y = 12,     w = 4 },
      { letter = 'S',     x = 86,      y = 12,     w = 3 },
      { letter = 'T',     x = 90,      y = 12,     w = 5 },
      { letter = 'U',     x = 96,      y = 12,     w = 4 },
      { letter = 'V',     x = 101,     y = 12,     w = 5 },
      { letter = 'W',     x = 107,     y = 12,     w = 5 },
      { letter = 'X',     x = 113,     y = 12,     w = 5 },
      { letter = 'Y',     x = 119,     y = 12,     w = 5 },
      { letter = 'Z',     x = 125,     y = 12,     w = 4 },
      { letter = '[',     x = 130,     y = 12,     w = 2 },
      { letter = '\\',    x = 134,     y = 12,     w = 3 },
      { letter = ']',     x = 137,     y = 12,     w = 3 },
      { letter = '^',     x = 143,     y = 12,     w = 3 },
      { letter = '_',     x = 148,     y = 12,     w = 3 },
      { letter = '`',     x = 154,     y = 12,     w = 2 },

      { letter = 'a',     x = 1,       y = 23,     w = 4 },
      { letter = 'b',     x = 6,       y = 23,     w = 3 },
      { letter = 'c',     x = 10,      y = 23,     w = 3 },
      { letter = 'd',     x = 14,      y = 23,     w = 3 },
      { letter = 'e',     x = 18,      y = 23,     w = 3 },
      { letter = 'f',     x = 22,      y = 23,     w = 3 },
      { letter = 'g',     x = 25,      y = 23,     w = 3 },
      { letter = 'h',     x = 29,      y = 23,     w = 3 },
      { letter = 'i',     x = 33,      y = 23,     w = 1 },
      { letter = 'j',     x = 34,      y = 23,     w = 2 },
      { letter = 'k',     x = 37,      y = 23,     w = 3 },
      { letter = 'l',     x = 41,      y = 23,     w = 1 },
      { letter = 'm',     x = 44,      y = 23,     w = 5 },
      { letter = 'n',     x = 51,      y = 23,     w = 3 },
      { letter = 'o',     x = 55,      y = 23,     w = 3 },
      { letter = 'p',     x = 59,      y = 23,     w = 3 },
      { letter = 'q',     x = 63,      y = 23,     w = 3 },
      { letter = 'r',     x = 67,      y = 23,     w = 2 },
      { letter = 's',     x = 70,      y = 23,     w = 2 },
      { letter = 't',     x = 73,      y = 23,     w = 2 },
      { letter = 'u',     x = 76,      y = 23,     w = 4 },
      { letter = 'v',     x = 80,      y = 23,     w = 3 },
      { letter = 'w',     x = 84,      y = 23,     w = 5 },
      { letter = 'x',     x = 90,      y = 23,     w = 3 },
      { letter = 'y',     x = 94,      y = 23,     w = 3 },
      { letter = 'z',     x = 98,      y = 23,     w = 2 },
      { letter = '{',     x = 102,     y = 23,     w = 3 },
      { letter = '|',     x = 107,     y = 23,     w = 1 },
      { letter = '}',     x = 110,     y = 23,     w = 3 },
      { letter = '~',     x = 115,     y = 23,     w = 4 },
      { letter = ' ',     x = 127,     y = 23,     w = 2 },

      { letter = 'à',     x = 1,       y = 33,     w = 4 },
      { letter = 'á',     x = 6,       y = 33,     w = 4 },
      { letter = 'â',     x = 11,      y = 33,     w = 4 },
      { letter = 'ã',     x = 16,      y = 33,     w = 4 },
      { letter = 'ç',     x = 25,      y = 33,     w = 3 },
      { letter = 'ê',     x = 32,      y = 33,     w = 3 },
      { letter = 'è',     x = 36,      y = 33,     w = 3 },
      { letter = 'é',     x = 40,      y = 33,     w = 3 },
      { letter = 'ë',     x = 44,      y = 33,     w = 3 },
      { letter = 'ì',     x = 48,      y = 33,     w = 2 },
      { letter = 'í',     x = 52,      y = 33,     w = 2 },
      { letter = 'î',     x = 55,      y = 33,     w = 3 },
      { letter = 'ï',     x = 59,      y = 33,     w = 3 },
      { letter = 'ò',     x = 64,      y = 33,     w = 3 },
      { letter = 'ó',     x = 68,      y = 33,     w = 3 },
      { letter = 'ô',     x = 72,      y = 33,     w = 3 },
      { letter = 'õ',     x = 76,      y = 33,     w = 3 },
      { letter = 'ù',     x = 80,      y = 33,     w = 4 },
      { letter = 'ú',     x = 84,      y = 33,     w = 4 },
      { letter = 'û',     x = 88,      y = 33,     w = 4 },
      { letter = 'ü',     x = 92,      y = 33,     w = 4 },

      { letter = 'À',     x = 1,      y = 42,      w = 4 },
      { letter = 'Á',     x = 6,      y = 42,      w = 4 },
      { letter = 'Â',     x = 11,     y = 42,      w = 4 },
      { letter = 'Ã',     x = 16,     y = 42,      w = 4 },
      { letter = 'Ç',     x = 25,     y = 42,      w = 4 },
      { letter = 'Ê',     x = 32,     y = 42,      w = 3 },
      { letter = 'È',     x = 36,     y = 42,      w = 3 },
      { letter = 'É',     x = 40,     y = 42,      w = 3 },
      { letter = 'Ë',     x = 44,     y = 42,      w = 3 },
      { letter = 'Ì',     x = 48,     y = 42,      w = 2 },
      { letter = 'Í',     x = 52,     y = 42,      w = 2 },
      { letter = 'Î',     x = 55,     y = 42,      w = 3 },
      { letter = 'Ï',     x = 59,     y = 42,      w = 3 },
      { letter = 'Ò',     x = 64,     y = 42,      w = 4 },
      { letter = 'Ó',     x = 69,     y = 42,      w = 4 },
      { letter = 'Ô',     x = 74,     y = 42,      w = 4 },
      { letter = 'Õ',     x = 79,     y = 42,      w = 4 },
      { letter = 'Ù',     x = 84,     y = 42,      w = 4 },
      { letter = 'Ú',     x = 89,     y = 42,      w = 4 },
      { letter = 'Û',     x = 94,     y = 42,      w = 4 },
      { letter = 'Ü',     x = 99,     y = 42,      w = 4 },
    }
  }

  rval = resources_load_font('small_font', small_font)
  print("load font: " .. tostring(rval))


  local font = {
    key = "font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 12,
    spacing = 1,
    letters = {
      { letter = '!',     x = 4,       y = 55,     w = 1 },
      { letter = '"',     x = 6,       y = 55,     w = 3 },
      { letter = '#',     x = 10,      y = 55,     w = 5 },
      { letter = '$',     x = 17,      y = 55,     w = 5 },
      { letter = '%',     x = 24,      y = 55,     w = 9 },
      { letter = '&',     x = 34,      y = 55,     w = 8 },
      { letter = '\'',    x = 44,      y = 55,     w = 1 },
      { letter = '(',     x = 47,      y = 55,     w = 2 },
      { letter = ')',     x = 50,      y = 55,     w = 2 },
      { letter = '*',     x = 54,      y = 55,     w = 3 },
      { letter = '+',     x = 59,      y = 55,     w = 3 },
      { letter = ',',     x = 63,      y = 55,     w = 2 },
      { letter = '-',     x = 66,      y = 55,     w = 2 },
      { letter = '.',     x = 69,      y = 55,     w = 2 },
      { letter = '/',     x = 72,      y = 55,     w = 3 },
      { letter = '1',     x = 77,      y = 55,     w = 3 },
      { letter = '2',     x = 81,      y = 55,     w = 4 },
      { letter = '3',     x = 86,      y = 55,     w = 4 },
      { letter = '4',     x = 91,      y = 55,     w = 4 },
      { letter = '5',     x = 96,      y = 55,     w = 4 },
      { letter = '6',     x = 101,     y = 55,     w = 4 },
      { letter = '7',     x = 106,     y = 55,     w = 4 },
      { letter = '8',     x = 111,     y = 55,     w = 4 },
      { letter = '9',     x = 116,     y = 55,     w = 4 },
      { letter = '0',     x = 121,     y = 55,     w = 4 },
      { letter = ':',     x = 126,     y = 55,     w = 2 },
      { letter = ';',     x = 129,     y = 55,     w = 2 },
      { letter = '<',     x = 133,     y = 55,     w = 3 },
      { letter = '=',     x = 137,     y = 55,     w = 3 },
      { letter = '>',     x = 141,     y = 55,     w = 3 },
      { letter = '?',     x = 145,     y = 55,     w = 4 },
      { letter = '@',     x = 151,     y = 55,     w = 7 },

      { letter = 'A',     x = 6,       y = 71,     w = 7 },
      { letter = 'B',     x = 14,      y = 71,     w = 6 },
      { letter = 'C',     x = 21,      y = 71,     w = 7 },
      { letter = 'D',     x = 29,      y = 71,     w = 7 },
      { letter = 'E',     x = 37,      y = 71,     w = 6 },
      { letter = 'F',     x = 44,      y = 71,     w = 6 },
      { letter = 'G',     x = 50,      y = 71,     w = 7 },
      { letter = 'H',     x = 58,      y = 71,     w = 7 },
      { letter = 'I',     x = 67,      y = 71,     w = 1 },
      { letter = 'J',     x = 69,      y = 71,     w = 4 },
      { letter = 'K',     x = 75,      y = 71,     w = 6 },
      { letter = 'L',     x = 82,      y = 71,     w = 5 },
      { letter = 'M',     x = 89,      y = 71,     w = 9 },
      { letter = 'N',     x = 100,     y = 71,     w = 7 },
      { letter = 'O',     x = 108,     y = 71,     w = 7 },
      { letter = 'P',     x = 116,     y = 71,     w = 6 },
      { letter = 'Q',     x = 123,     y = 71,     w = 10,    f = 7 },
      { letter = 'R',     x = 135,     y = 71,     w = 6 },
      { letter = 'S',     x = 143,     y = 71,     w = 6 },
      { letter = 'T',     x = 150,     y = 71,     w = 7 },
      { letter = 'U',     x = 158,     y = 71,     w = 7 },
      { letter = 'V',     x = 167,     y = 71,     w = 9 },
      { letter = 'W',     x = 178,     y = 71,     w = 9 },
      { letter = 'X',     x = 189,     y = 71,     w = 7 },
      { letter = 'Y',     x = 197,     y = 71,     w = 7 },
      { letter = 'Z',     x = 205,     y = 71,     w = 7 },
      { letter = '[',     x = 214,     y = 71,     w = 2 },
      { letter = '\\',    x = 218,     y = 71,     w = 3 },
      { letter = ']',     x = 222,     y = 71,     w = 2 },
      { letter = '^',     x = 227,     y = 71,     w = 3 },
      { letter = '_',     x = 232,     y = 71,     w = 3 },
      { letter = '`',     x = 238,     y = 71,     w = 2 },

      { letter = 'a',     x = 5,       y = 87,     w = 5 },
      { letter = 'b',     x = 11,      y = 87,     w = 4 },
      { letter = 'c',     x = 16,      y = 87,     w = 4 },
      { letter = 'd',     x = 21,      y = 87,     w = 4 },
      { letter = 'e',     x = 26,      y = 87,     w = 4 },
      { letter = 'f',     x = 31,      y = 87,     w = 5,     f = 4 },
      { letter = 'g',     x = 36,      y = 87,     w = 5 },
      { letter = 'h',     x = 43,      y = 87,     w = 4 },
      { letter = 'i',     x = 49,      y = 87,     w = 1 },
      { letter = 'j',     x = 52,      y = 87,     w = 2 },
      { letter = 'k',     x = 56,      y = 87,     w = 4 },
      { letter = 'l',     x = 61,      y = 87,     w = 1 },
      { letter = 'm',     x = 64,      y = 87,     w = 7 },
      { letter = 'n',     x = 72,      y = 87,     w = 4 },
      { letter = 'o',     x = 77,      y = 87,     w = 4 },
      { letter = 'p',     x = 82,      y = 87,     w = 4 },
      { letter = 'q',     x = 87,      y = 87,     w = 4 },
      { letter = 'r',     x = 92,      y = 87,     w = 4 },
      { letter = 's',     x = 97,      y = 87,     w = 4 },
      { letter = 't',     x = 102,     y = 87,     w = 4 },
      { letter = 'u',     x = 107,     y = 87,     w = 4 },
      { letter = 'v',     x = 112,     y = 87,     w = 5 },
      { letter = 'w',     x = 118,     y = 87,     w = 7 },
      { letter = 'x',     x = 126,     y = 87,     w = 5 },
      { letter = 'y',     x = 133,     y = 87,     w = 4 },
      { letter = 'z',     x = 138,     y = 87,     w = 5 },
      { letter = '{',     x = 145,     y = 87,     w = 3 },
      { letter = '|',     x = 150,     y = 87,     w = 1 },
      { letter = '}',     x = 153,     y = 87,     w = 3 },
      { letter = '~',     x = 158,     y = 87,     w = 4 },
      { letter = ' ',     x = 164,     y = 87,     w = 2 },

      { letter = 'à',     x = 5,       y = 103,     w = 5 },
      { letter = 'á',     x = 11,      y = 103,     w = 5 },
      { letter = 'â',     x = 16,      y = 103,     w = 5 },
      { letter = 'ã',     x = 23,      y = 103,     w = 5 },
      { letter = 'ç',     x = 30,      y = 103,     w = 4 },
      { letter = 'ê',     x = 36,      y = 103,     w = 4 },
      { letter = 'è',     x = 41,      y = 103,     w = 4 },
      { letter = 'é',     x = 46,      y = 103,     w = 4 },
      { letter = 'ë',     x = 51,      y = 103,     w = 4 },
      { letter = 'ì',     x = 58,      y = 103,     w = 2 },
      { letter = 'í',     x = 63,      y = 103,     w = 2 },
      { letter = 'î',     x = 66,      y = 103,     w = 3 },
      { letter = 'ï',     x = 70,      y = 103,     w = 3 },
      { letter = 'ò',     x = 76,      y = 103,     w = 4 },
      { letter = 'ó',     x = 81,      y = 103,     w = 4 },
      { letter = 'ô',     x = 86,      y = 103,     w = 4 },
      { letter = 'õ',     x = 91,      y = 103,     w = 4 },
      { letter = 'ù',     x = 97,      y = 103,     w = 4 },
      { letter = 'ú',     x = 102,     y = 103,     w = 4 },
      { letter = 'û',     x = 107,     y = 103,     w = 4 },
      { letter = 'ü',     x = 112,     y = 103,     w = 4 },

      { letter = 'À',     x = 5,       y = 119,     w = 7 },
      { letter = 'Á',     x = 13,      y = 119,     w = 7 },
      { letter = 'Â',     x = 21,      y = 119,     w = 7 },
      { letter = 'Ã',     x = 29,      y = 119,     w = 7 },
      { letter = 'Ç',     x = 38,      y = 119,     w = 7 },
      { letter = 'Ê',     x = 47,      y = 119,     w = 6 },
      { letter = 'È',     x = 54,      y = 119,     w = 6 },
      { letter = 'É',     x = 61,      y = 119,     w = 6 },
      { letter = 'Ë',     x = 68,      y = 119,     w = 6 },
      { letter = 'Ì',     x = 76,      y = 119,     w = 2 },
      { letter = 'Í',     x = 81,      y = 119,     w = 2 },
      { letter = 'Î',     x = 84,      y = 119,     w = 3 },
      { letter = 'Ï',     x = 88,      y = 119,     w = 3 },
      { letter = 'Ò',     x = 93,      y = 119,     w = 7 },
      { letter = 'Ó',     x = 101,     y = 119,     w = 7 },
      { letter = 'Ô',     x = 109,     y = 119,     w = 7 },
      { letter = 'Õ',     x = 117,     y = 119,     w = 7 },
      { letter = 'Ù',     x = 126,     y = 119,     w = 7 },
      { letter = 'Ú',     x = 134,     y = 119,     w = 7 },
      { letter = 'Û',     x = 142,     y = 119,     w = 7 },
      { letter = 'Ü',     x = 150,     y = 119,     w = 7 },
    }
  }

  rval = resources_load_font('font', font)
  print("load font: " .. tostring(rval))


  return rval
end

return Resources
