

local Resources = {}

function Resources:load_assets()
  local textures = {
    { key = "sprites",      path = "games/napoleonic/assets/textures/sprites.png" },
    { key = "tiles",        path = "games/napoleonic/assets/textures/tiles.png" },
    { key = "effects",      path = "games/napoleonic/assets/textures/effects.png" },
    { key = "gui",          path = "games/napoleonic/assets/textures/gui.png" },
  }

  local sounds = {
    { key = "fire",         path = "games/napoleonic/assets/sounds/fire.wav" },
  }

  local music = {
    { key = "adagio",       path = "games/napoleonic/assets/music/adagio.wav" },
  }

  local texture_rval = true
  for index, elm in ipairs(textures) do
    if elm.smooth == nil then
      elm.smooth = false
    end
    texture_rval = texture_rval and resources_load_texture(elm.key, elm.path, elm.smooth)
  end
  print("load textures: " .. tostring(texture_rval))

  local sounds_rval = true
  for index, elm in ipairs(sounds) do
    sounds_rval = sounds_rval and resources_load_sound(elm.key, elm.path)
  end
  print("load sounds: " .. tostring(sounds_rval))

  local music_rval = true
  for index, elm in ipairs(music) do
    music_rval = music_rval and resources_load_music(elm.key, elm.path)
  end
  print("load music: " .. tostring(music_rval))

  return texture_rval and sounds_rval and music_rval
end


function Resources:load_font()
  local small_font = {
    key = "small_font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 8,
    spacing = 1,
    letters = {
      { letter = '!',     x = 1,       y = 1,      w = 1 },
      { letter = '"',     x = 3,       y = 1,      w = 3 },
      { letter = '#',     x = 8,       y = 1,      w = 4 },
      { letter = '$',     x = 14,      y = 1,      w = 3 },
      { letter = '%',     x = 19,      y = 1,      w = 5 },
      { letter = '&',     x = 26,      y = 1,      w = 5 },
      { letter = '\'',    x = 32,      y = 1,      w = 1 },
      { letter = '(',     x = 35,      y = 1,      w = 2 },
      { letter = ')',     x = 38,      y = 1,      w = 2 },
      { letter = '*',     x = 42,      y = 1,      w = 3 },
      { letter = '+',     x = 47,      y = 1,      w = 3 },
      { letter = ',',     x = 51,      y = 1,      w = 2 },
      { letter = '-',     x = 54,      y = 1,      w = 2 },
      { letter = '.',     x = 57,      y = 1,      w = 1 },
      { letter = '/',     x = 60,      y = 1,      w = 3 },
      { letter = '1',     x = 65,      y = 1,      w = 3 },
      { letter = '2',     x = 69,      y = 1,      w = 4 },
      { letter = '3',     x = 74,      y = 1,      w = 4 },
      { letter = '4',     x = 79,      y = 1,      w = 4 },
      { letter = '5',     x = 84,      y = 1,      w = 4 },
      { letter = '6',     x = 89,      y = 1,      w = 4 },
      { letter = '7',     x = 94,      y = 1,      w = 3 },
      { letter = '8',     x = 98,      y = 1,      w = 4 },
      { letter = '9',     x = 103,     y = 1,      w = 4 },
      { letter = '0',     x = 108,     y = 1,      w = 4 },
      { letter = ':',     x = 114,     y = 1,      w = 1 },
      { letter = ';',     x = 116,     y = 1,      w = 2 },
      { letter = '<',     x = 120,     y = 1,      w = 3 },
      { letter = '=',     x = 124,     y = 1,      w = 3 },
      { letter = '>',     x = 128,     y = 1,      w = 3 },
      { letter = '?',     x = 132,     y = 1,      w = 4 },
      { letter = '@',     x = 137,     y = 1,      w = 6 },

      { letter = 'A',     x = 1,       y = 12,     w = 4 },
      { letter = 'B',     x = 6,       y = 12,     w = 4 },
      { letter = 'C',     x = 11,      y = 12,     w = 3 },
      { letter = 'D',     x = 15,      y = 12,     w = 4 },
      { letter = 'E',     x = 20,      y = 12,     w = 3 },
      { letter = 'F',     x = 24,      y = 12,     w = 3 },
      { letter = 'G',     x = 28,      y = 12,     w = 4 },
      { letter = 'H',     x = 33,      y = 12,     w = 4 },
      { letter = 'I',     x = 38,      y = 12,     w = 1 },
      { letter = 'J',     x = 40,      y = 12,     w = 4 },
      { letter = 'K',     x = 45,      y = 12,     w = 4 },
      { letter = 'L',     x = 50,      y = 12,     w = 3 },
      { letter = 'M',     x = 54,      y = 12,     w = 5 },
      { letter = 'N',     x = 60,      y = 12,     w = 4 },
      { letter = 'O',     x = 65,      y = 12,     w = 4 },
      { letter = 'P',     x = 70,      y = 12,     w = 4 },
      { letter = 'Q',     x = 75,      y = 12,     w = 5 },
      -- { letter = 'Q',     x = 160,     y = 12,     w = 7,      f = 5 },
      { letter = 'R',     x = 81,      y = 12,     w = 4 },
      { letter = 'S',     x = 86,      y = 12,     w = 3 },
      { letter = 'T',     x = 90,      y = 12,     w = 5 },
      { letter = 'U',     x = 96,      y = 12,     w = 4 },
      { letter = 'V',     x = 101,     y = 12,     w = 5 },
      { letter = 'W',     x = 107,     y = 12,     w = 5 },
      { letter = 'X',     x = 113,     y = 12,     w = 5 },
      { letter = 'Y',     x = 119,     y = 12,     w = 5 },
      { letter = 'Z',     x = 125,     y = 12,     w = 4 },
      { letter = '[',     x = 130,     y = 12,     w = 2 },
      { letter = '\\',    x = 134,     y = 12,     w = 3 },
      { letter = ']',     x = 137,     y = 12,     w = 3 },
      { letter = '^',     x = 143,     y = 12,     w = 3 },
      { letter = '_',     x = 148,     y = 12,     w = 3 },
      { letter = '`',     x = 154,     y = 12,     w = 2 },

      { letter = 'a',     x = 1,       y = 23,     w = 4 },
      { letter = 'b',     x = 6,       y = 23,     w = 3 },
      { letter = 'c',     x = 10,      y = 23,     w = 3 },
      { letter = 'd',     x = 14,      y = 23,     w = 3 },
      { letter = 'e',     x = 18,      y = 23,     w = 3 },
      { letter = 'f',     x = 22,      y = 23,     w = 3 },
      { letter = 'g',     x = 25,      y = 23,     w = 3 },
      { letter = 'h',     x = 29,      y = 23,     w = 3 },
      { letter = 'i',     x = 33,      y = 23,     w = 1 },
      { letter = 'j',     x = 34,      y = 23,     w = 2 },
      { letter = 'k',     x = 37,      y = 23,     w = 3 },
      { letter = 'l',     x = 41,      y = 23,     w = 1 },
      { letter = 'm',     x = 44,      y = 23,     w = 5 },
      { letter = 'n',     x = 51,      y = 23,     w = 3 },
      { letter = 'o',     x = 55,      y = 23,     w = 3 },
      { letter = 'p',     x = 59,      y = 23,     w = 3 },
      { letter = 'q',     x = 63,      y = 23,     w = 3 },
      { letter = 'r',     x = 67,      y = 23,     w = 2 },
      { letter = 's',     x = 70,      y = 23,     w = 2 },
      { letter = 't',     x = 73,      y = 23,     w = 2 },
      { letter = 'u',     x = 76,      y = 23,     w = 4 },
      { letter = 'v',     x = 80,      y = 23,     w = 3 },
      { letter = 'w',     x = 84,      y = 23,     w = 5 },
      { letter = 'x',     x = 90,      y = 23,     w = 3 },
      { letter = 'y',     x = 94,      y = 23,     w = 3 },
      { letter = 'z',     x = 98,      y = 23,     w = 2 },
      { letter = '{',     x = 102,     y = 23,     w = 3 },
      { letter = '|',     x = 107,     y = 23,     w = 1 },
      { letter = '}',     x = 110,     y = 23,     w = 3 },
      { letter = '~',     x = 115,     y = 23,     w = 4 },
      { letter = ' ',     x = 127,     y = 23,     w = 2 },

      { letter = 'à',     x = 1,       y = 33,     w = 4 },
      { letter = 'á',     x = 6,       y = 33,     w = 4 },
      { letter = 'â',     x = 11,      y = 33,     w = 4 },
      { letter = 'ã',     x = 16,      y = 33,     w = 4 },
      { letter = 'ç',     x = 25,      y = 33,     w = 3 },
      { letter = 'ê',     x = 32,      y = 33,     w = 3 },
      { letter = 'è',     x = 36,      y = 33,     w = 3 },
      { letter = 'é',     x = 40,      y = 33,     w = 3 },
      { letter = 'ë',     x = 44,      y = 33,     w = 3 },
      { letter = 'ì',     x = 48,      y = 33,     w = 2 },
      { letter = 'í',     x = 52,      y = 33,     w = 2 },
      { letter = 'î',     x = 55,      y = 33,     w = 3 },
      { letter = 'ï',     x = 59,      y = 33,     w = 3 },
      { letter = 'ò',     x = 64,      y = 33,     w = 3 },
      { letter = 'ó',     x = 68,      y = 33,     w = 3 },
      { letter = 'ô',     x = 72,      y = 33,     w = 3 },
      { letter = 'õ',     x = 76,      y = 33,     w = 3 },
      { letter = 'ù',     x = 80,      y = 33,     w = 4 },
      { letter = 'ú',     x = 84,      y = 33,     w = 4 },
      { letter = 'û',     x = 88,      y = 33,     w = 4 },
      { letter = 'ü',     x = 92,      y = 33,     w = 4 },

      { letter = 'À',     x = 1,      y = 42,      w = 4 },
      { letter = 'Á',     x = 6,      y = 42,      w = 4 },
      { letter = 'Â',     x = 11,     y = 42,      w = 4 },
      { letter = 'Ã',     x = 16,     y = 42,      w = 4 },
      { letter = 'Ç',     x = 25,     y = 42,      w = 4 },
      { letter = 'Ê',     x = 32,     y = 42,      w = 3 },
      { letter = 'È',     x = 36,     y = 42,      w = 3 },
      { letter = 'É',     x = 40,     y = 42,      w = 3 },
      { letter = 'Ë',     x = 44,     y = 42,      w = 3 },
      { letter = 'Ì',     x = 48,     y = 42,      w = 2 },
      { letter = 'Í',     x = 52,     y = 42,      w = 2 },
      { letter = 'Î',     x = 55,     y = 42,      w = 3 },
      { letter = 'Ï',     x = 59,     y = 42,      w = 3 },
      { letter = 'Ò',     x = 64,     y = 42,      w = 4 },
      { letter = 'Ó',     x = 69,     y = 42,      w = 4 },
      { letter = 'Ô',     x = 74,     y = 42,      w = 4 },
      { letter = 'Õ',     x = 79,     y = 42,      w = 4 },
      { letter = 'Ù',     x = 84,     y = 42,      w = 4 },
      { letter = 'Ú',     x = 89,     y = 42,      w = 4 },
      { letter = 'Û',     x = 94,     y = 42,      w = 4 },
      { letter = 'Ü',     x = 99,     y = 42,      w = 4 },
    }
  }

  rval = resources_load_font('small_font', small_font)
  print("load font: " .. tostring(rval))


  local font = {
    key = "font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 12,
    spacing = 1,
    letters = {
      { letter = '!',     x = 4,       y = 55,     w = 1 },
      { letter = '"',     x = 6,       y = 55,     w = 3 },
      { letter = '#',     x = 10,      y = 55,     w = 5 },
      { letter = '$',     x = 17,      y = 55,     w = 5 },
      { letter = '%',     x = 24,      y = 55,     w = 9 },
      { letter = '&',     x = 34,      y = 55,     w = 8 },
      { letter = '\'',    x = 44,      y = 55,     w = 1 },
      { letter = '(',     x = 47,      y = 55,     w = 2 },
      { letter = ')',     x = 50,      y = 55,     w = 2 },
      { letter = '*',     x = 54,      y = 55,     w = 3 },
      { letter = '+',     x = 59,      y = 55,     w = 3 },
      { letter = ',',     x = 63,      y = 55,     w = 2 },
      { letter = '-',     x = 66,      y = 55,     w = 2 },
      { letter = '.',     x = 69,      y = 55,     w = 2 },
      { letter = '/',     x = 72,      y = 55,     w = 3 },
      { letter = '1',     x = 77,      y = 55,     w = 3 },
      { letter = '2',     x = 81,      y = 55,     w = 4 },
      { letter = '3',     x = 86,      y = 55,     w = 4 },
      { letter = '4',     x = 91,      y = 55,     w = 4 },
      { letter = '5',     x = 96,      y = 55,     w = 4 },
      { letter = '6',     x = 101,     y = 55,     w = 4 },
      { letter = '7',     x = 106,     y = 55,     w = 4 },
      { letter = '8',     x = 111,     y = 55,     w = 4 },
      { letter = '9',     x = 116,     y = 55,     w = 4 },
      { letter = '0',     x = 121,     y = 55,     w = 4 },
      { letter = ':',     x = 126,     y = 55,     w = 2 },
      { letter = ';',     x = 129,     y = 55,     w = 2 },
      { letter = '<',     x = 133,     y = 55,     w = 3 },
      { letter = '=',     x = 137,     y = 55,     w = 3 },
      { letter = '>',     x = 141,     y = 55,     w = 3 },
      { letter = '?',     x = 145,     y = 55,     w = 4 },
      { letter = '@',     x = 151,     y = 55,     w = 7 },

      { letter = 'A',     x = 6,       y = 71,     w = 7 },
      { letter = 'B',     x = 14,      y = 71,     w = 6 },
      { letter = 'C',     x = 21,      y = 71,     w = 7 },
      { letter = 'D',     x = 29,      y = 71,     w = 7 },
      { letter = 'E',     x = 37,      y = 71,     w = 6 },
      { letter = 'F',     x = 44,      y = 71,     w = 6 },
      { letter = 'G',     x = 50,      y = 71,     w = 7 },
      { letter = 'H',     x = 58,      y = 71,     w = 7 },
      { letter = 'I',     x = 67,      y = 71,     w = 1 },
      { letter = 'J',     x = 69,      y = 71,     w = 4 },
      { letter = 'K',     x = 75,      y = 71,     w = 6 },
      { letter = 'L',     x = 82,      y = 71,     w = 5 },
      { letter = 'M',     x = 89,      y = 71,     w = 9 },
      { letter = 'N',     x = 100,     y = 71,     w = 7 },
      { letter = 'O',     x = 108,     y = 71,     w = 7 },
      { letter = 'P',     x = 116,     y = 71,     w = 6,     f = 5 },
      { letter = 'Q',     x = 123,     y = 71,     w = 10,    f = 7 },
      { letter = 'R',     x = 135,     y = 71,     w = 6 },
      { letter = 'S',     x = 143,     y = 71,     w = 6 },
      { letter = 'T',     x = 150,     y = 71,     w = 7 },
      { letter = 'U',     x = 158,     y = 71,     w = 7 },
      { letter = 'V',     x = 167,     y = 71,     w = 9,     f = 8 },
      { letter = 'W',     x = 178,     y = 71,     w = 9 },
      { letter = 'X',     x = 189,     y = 71,     w = 7 },
      { letter = 'Y',     x = 197,     y = 71,     w = 7 },
      { letter = 'Z',     x = 205,     y = 71,     w = 7 },
      { letter = '[',     x = 214,     y = 71,     w = 2 },
      { letter = '\\',    x = 218,     y = 71,     w = 3 },
      { letter = ']',     x = 222,     y = 71,     w = 2 },
      { letter = '^',     x = 227,     y = 71,     w = 3 },
      { letter = '_',     x = 232,     y = 71,     w = 3 },
      { letter = '`',     x = 238,     y = 71,     w = 2 },

      { letter = 'a',     x = 5,       y = 87,     w = 5,     f = 4 },
      { letter = 'b',     x = 11,      y = 87,     w = 4 },
      { letter = 'c',     x = 16,      y = 87,     w = 4 },
      { letter = 'd',     x = 21,      y = 87,     w = 4 },
      { letter = 'e',     x = 26,      y = 87,     w = 4 },
      { letter = 'f',     x = 31,      y = 87,     w = 5,     f = 3 },
      { letter = 'g',     x = 36,      y = 87,     w = 5 },
      { letter = 'h',     x = 43,      y = 87,     w = 4 },
      { letter = 'i',     x = 49,      y = 87,     w = 1 },
      { letter = 'j',     x = 52,      y = 87,     w = 2 },
      { letter = 'k',     x = 56,      y = 87,     w = 4 },
      { letter = 'l',     x = 61,      y = 87,     w = 1 },
      { letter = 'm',     x = 64,      y = 87,     w = 7 },
      { letter = 'n',     x = 72,      y = 87,     w = 4 },
      { letter = 'o',     x = 77,      y = 87,     w = 4 },
      { letter = 'p',     x = 82,      y = 87,     w = 4 },
      { letter = 'q',     x = 87,      y = 87,     w = 4 },
      { letter = 'r',     x = 92,      y = 87,     w = 4 },
      { letter = 's',     x = 97,      y = 87,     w = 4 },
      { letter = 't',     x = 102,     y = 87,     w = 4,             b = 0 },
      { letter = 'u',     x = 107,     y = 87,     w = 4 },
      { letter = 'v',     x = 112,     y = 87,     w = 5 },
      { letter = 'w',     x = 118,     y = 87,     w = 7 },
      { letter = 'x',     x = 126,     y = 87,     w = 5 },
      { letter = 'y',     x = 133,     y = 87,     w = 4 },
      { letter = 'z',     x = 138,     y = 87,     w = 5 },
      { letter = '{',     x = 145,     y = 87,     w = 3 },
      { letter = '|',     x = 150,     y = 87,     w = 1 },
      { letter = '}',     x = 153,     y = 87,     w = 3 },
      { letter = '~',     x = 158,     y = 87,     w = 4 },
      { letter = ' ',     x = 164,     y = 87,     w = 2 },

      { letter = 'à',     x = 5,       y = 103,     w = 5 },
      { letter = 'á',     x = 11,      y = 103,     w = 5 },
      { letter = 'â',     x = 16,      y = 103,     w = 5 },
      { letter = 'ã',     x = 23,      y = 103,     w = 5 },
      { letter = 'ç',     x = 30,      y = 103,     w = 4 },
      { letter = 'ê',     x = 36,      y = 103,     w = 4 },
      { letter = 'è',     x = 41,      y = 103,     w = 4 },
      { letter = 'é',     x = 46,      y = 103,     w = 4 },
      { letter = 'ë',     x = 51,      y = 103,     w = 4 },
      { letter = 'ì',     x = 58,      y = 103,     w = 2 },
      { letter = 'í',     x = 63,      y = 103,     w = 2 },
      { letter = 'î',     x = 66,      y = 103,     w = 3 },
      { letter = 'ï',     x = 70,      y = 103,     w = 3 },
      { letter = 'ò',     x = 76,      y = 103,     w = 4 },
      { letter = 'ó',     x = 81,      y = 103,     w = 4 },
      { letter = 'ô',     x = 86,      y = 103,     w = 4 },
      { letter = 'õ',     x = 91,      y = 103,     w = 4 },
      { letter = 'ù',     x = 97,      y = 103,     w = 4 },
      { letter = 'ú',     x = 102,     y = 103,     w = 4 },
      { letter = 'û',     x = 107,     y = 103,     w = 4 },
      { letter = 'ü',     x = 112,     y = 103,     w = 4 },

      { letter = 'À',     x = 5,       y = 119,     w = 7 },
      { letter = 'Á',     x = 13,      y = 119,     w = 7 },
      { letter = 'Â',     x = 21,      y = 119,     w = 7 },
      { letter = 'Ã',     x = 29,      y = 119,     w = 7 },
      { letter = 'Ç',     x = 38,      y = 119,     w = 7 },
      { letter = 'Ê',     x = 47,      y = 119,     w = 6 },
      { letter = 'È',     x = 54,      y = 119,     w = 6 },
      { letter = 'É',     x = 61,      y = 119,     w = 6 },
      { letter = 'Ë',     x = 68,      y = 119,     w = 6 },
      { letter = 'Ì',     x = 76,      y = 119,     w = 2 },
      { letter = 'Í',     x = 81,      y = 119,     w = 2 },
      { letter = 'Î',     x = 84,      y = 119,     w = 3 },
      { letter = 'Ï',     x = 88,      y = 119,     w = 3 },
      { letter = 'Ò',     x = 93,      y = 119,     w = 7 },
      { letter = 'Ó',     x = 101,     y = 119,     w = 7 },
      { letter = 'Ô',     x = 109,     y = 119,     w = 7 },
      { letter = 'Õ',     x = 117,     y = 119,     w = 7 },
      { letter = 'Ù',     x = 126,     y = 119,     w = 7 },
      { letter = 'Ú',     x = 134,     y = 119,     w = 7 },
      { letter = 'Û',     x = 142,     y = 119,     w = 7 },
      { letter = 'Ü',     x = 150,     y = 119,     w = 7 },
    }
  }

  rval = resources_load_font('font', font)
  print("load font: " .. tostring(rval))

  local small_cursive_font = {
    key = "small_cursive_font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 20,
    spacing = 0,
    letters = {
      { letter = '!',     x = 7,       y = 291,     w = 6 },
      { letter = '"',     x = 13,      y = 291,     w = 5 },
      { letter = '#',     x = 18,      y = 291,     w = 10 },
      { letter = '$',     x = 27,      y = 291,     w = 8 },
      { letter = '%',     x = 35,      y = 291,     w = 11 },
      { letter = '&',     x = 46,      y = 291,     w = 12,      f = 9 },
      { letter = '\'',    x = 58,      y = 291,     w = 3 },
      { letter = '(',     x = 62,      y = 291,     w = 5 },
      { letter = ')',     x = 67,      y = 291,     w = 5 },
      { letter = '+',     x = 72,      y = 291,     w = 7 },
      { letter = '*',     x = 79,      y = 291,     w = 7 },
      { letter = ',',     x = 84,      y = 291,     w = 4 },
      { letter = '-',     x = 88,      y = 291,     w = 7 },
      { letter = '.',     x = 95,      y = 291,     w = 4 },
      { letter = '/',     x = 99,      y = 291,     w = 8 },
      { letter = '1',     x = 108,     y = 291,     w = 7 },
      { letter = '2',     x = 115,     y = 291,     w = 10 },
      { letter = '3',     x = 125,     y = 291,     w = 9 },
      { letter = '4',     x = 136,     y = 291,     w = 8 },
      { letter = '5',     x = 144,     y = 291,     w = 8 },
      { letter = '6',     x = 153,     y = 291,     w = 8 },
      { letter = '7',     x = 162,     y = 291,     w = 10,                    b = 2 },
      { letter = '8',     x = 173,     y = 291,     w = 8 },
      { letter = '9',     x = 182,     y = 291,     w = 9,                     b = 2 },
      { letter = '0',     x = 193,     y = 291,     w = 8 },
      { letter = ':',     x = 204,     y = 291,     w = 5 },
      { letter = ';',     x = 210,     y = 291,     w = 5 },
      { letter = '<',     x = 216,     y = 291,     w = 7 },
      { letter = '>',     x = 224,     y = 291,     w = 7 },
      { letter = '=',     x = 231,     y = 291,     w = 7 },
      { letter = '?',     x = 241,     y = 291,     w = 7 },
      { letter = '@',     x = 252,     y = 291,     w = 12 },

      { letter = 'A',     x = 7,       y = 323,     w = 17,      f = 14 },
      { letter = 'B',     x = 25,      y = 323,     w = 13,      f = 12 },
      { letter = 'C',     x = 39,      y = 323,     w = 12,      f = 11 },
      { letter = 'D',     x = 54,      y = 323,     w = 14,      f = 13 },
      { letter = 'E',     x = 70,      y = 323,     w = 11,      f = 11 },
      { letter = 'F',     x = 83,      y = 323,     w = 14,      f = 11 },
      { letter = 'G',     x = 98,      y = 323,     w = 14,      f = 12 },
      { letter = 'H',     x = 114,     y = 323,     w = 18,      f = 16 },
      { letter = 'I',     x = 135,     y = 323,     w = 12,      f = 10 },
      { letter = 'J',     x = 149,     y = 323,     w = 12,      f = 10 },
      { letter = 'K',     x = 166,     y = 323,     w = 18,      f = 16 },
      { letter = 'L',     x = 185,     y = 323,     w = 14 },
      { letter = 'M',     x = 201,     y = 323,     w = 17 },
      { letter = 'N',     x = 220,     y = 323,     w = 16,      f = 15 },
      { letter = 'O',     x = 239,     y = 323,     w = 12,      f = 12 },
      { letter = 'P',     x = 254,     y = 323,     w = 13,      f = 11 },
      { letter = 'Q',     x = 269,     y = 323,     w = 13,      f = 13 },
      { letter = 'R',     x = 284,     y = 323,     w = 14,      f = 13 },
      { letter = 'S',     x = 301,     y = 323,     w = 13,      f = 13 },
      { letter = 'T',     x = 319,     y = 323,     w = 14,      f = 10 },
      { letter = 'U',     x = 334,     y = 323,     w = 14,      f = 13 },
      { letter = 'V',     x = 350,     y = 323,     w = 14,      f = 11 },
      { letter = 'W',     x = 365,     y = 323,     w = 17,      f = 14 },
      { letter = 'X',     x = 383,     y = 323,     w = 14,      f = 13 },
      { letter = 'Y',     x = 400,     y = 323,     w = 14,      f = 12 },
      { letter = 'Z',     x = 419,     y = 323,     w = 12,      f = 11 },
      { letter = '[',     x = 435,     y = 323,     w = 6 },
      { letter = '\\',    x = 443,     y = 323,     w = 5 },
      { letter = ']',     x = 450,     y = 323,     w = 6 },
      { letter = '^',     x = 459,     y = 323,     w = 4 },
      { letter = '_',     x = 465,     y = 323,     w = 4 },
      { letter = '`',     x = 473,     y = 323,     w = 3 },

      { letter = 'a',     x = 6,       y = 355,     w = 7 },
      { letter = 'b',     x = 14,      y = 355,     w = 6 },
      { letter = 'c',     x = 22,      y = 355,     w = 6 },
      { letter = 'd',     x = 29,      y = 355,     w = 8 },
      { letter = 'e',     x = 38,      y = 355,     w = 6 },
      { letter = 'f',     x = 45,      y = 355,     w = 9,       f = 8,      b = 3 },
      { letter = 'g',     x = 56,      y = 355,     w = 9,                   b = 2 },
      { letter = 'h',     x = 67,      y = 355,     w = 7 },
      { letter = 'i',     x = 75,      y = 355,     w = 5 },
      { letter = 'j',     x = 80,      y = 355,     w = 9,                   b = 4 },
      { letter = 'k',     x = 90,      y = 355,     w = 7 },
      { letter = 'l',     x = 98,      y = 355,     w = 7,       f = 6,      b = 1 },
      { letter = 'm',     x = 108,     y = 355,     w = 12 },
      { letter = 'n',     x = 121,     y = 355,     w = 9 },
      { letter = 'o',     x = 132,     y = 355,     w = 6 },
      { letter = 'p',     x = 139,     y = 355,     w = 11,                  b = 3},
      { letter = 'q',     x = 152,     y = 355,     w = 8 },
      { letter = 'r',     x = 162,     y = 355,     w = 7 },
      { letter = 's',     x = 171,     y = 355,     w = 6,                   b = 0 },
      { letter = 't',     x = 179,     y = 355,     w = 5 },
      { letter = 'u',     x = 185,     y = 355,     w = 7 },
      { letter = 'v',     x = 193,     y = 355,     w = 6 },
      { letter = 'w',     x = 200,     y = 355,     w = 9 },
      { letter = 'x',     x = 211,     y = 355,     w = 6 },
      { letter = 'y',     x = 219,     y = 355,     w = 8,                   b = 2 },
      { letter = 'z',     x = 228,     y = 355,     w = 8,                   b = 2 },
      { letter = '{',     x = 237,     y = 355,     w = 7 },
      { letter = '|',     x = 244,     y = 355,     w = 5 },
      { letter = '}',     x = 250,     y = 355,     w = 7 },
      { letter = '~',     x = 259,     y = 355,     w = 5 },
      { letter = ' ',     x = 266,     y = 355,     w = 5 },

      { letter = 'à',     x = 6,       y = 387,     w = 7 },
      { letter = 'á',     x = 14,      y = 387,     w = 7 },
      { letter = 'â',     x = 22,      y = 387,     w = 7 },
      { letter = 'ã',     x = 30,      y = 387,     w = 7 },
      { letter = 'ç',     x = 39,      y = 387,     w = 6 },
      { letter = 'ê',     x = 47,      y = 387,     w = 6 },
      { letter = 'è',     x = 54,      y = 387,     w = 6 },
      { letter = 'é',     x = 61,      y = 387,     w = 6 },
      { letter = 'ë',     x = 68,      y = 387,     w = 6 },
      { letter = 'ì',     x = 77,      y = 387,     w = 5 },
      { letter = 'í',     x = 83,      y = 387,     w = 5 },
      { letter = 'î',     x = 89,      y = 387,     w = 5 },
      { letter = 'ï',     x = 95,      y = 387,     w = 5 },
      { letter = 'ò',     x = 102,     y = 387,     w = 6 },
      { letter = 'ó',     x = 110,     y = 387,     w = 6 },
      { letter = 'ô',     x = 118,     y = 387,     w = 6 },
      { letter = 'õ',     x = 126,     y = 387,     w = 6 },
      { letter = 'ù',     x = 134,     y = 387,     w = 7 },
      { letter = 'ú',     x = 143,     y = 387,     w = 7 },
      { letter = 'û',     x = 152,     y = 387,     w = 7 },
      { letter = 'ü',     x = 161,     y = 387,     w = 7 },

      { letter = 'À',     x = 5,       y = 419,     w = 17,      f = 14 },
      { letter = 'Á',     x = 23,      y = 419,     w = 20,      f = 14 },
      { letter = 'Â',     x = 44,      y = 419,     w = 17,      f = 14 },
      { letter = 'Ã',     x = 63,      y = 419,     w = 17,      f = 14 },
      { letter = 'Ç',     x = 82,      y = 419,     w = 12,      f = 11 },
      { letter = 'Ê',     x = 96,      y = 419,     w = 11,      f = 11 },
      { letter = 'È',     x = 109,     y = 419,     w = 11,      f = 11 },
      { letter = 'É',     x = 121,     y = 419,     w = 11,      f = 11 },
      { letter = 'Ë',     x = 133,     y = 419,     w = 11,      f = 11 },
      { letter = 'Ì',     x = 146,     y = 419,     w = 12,      f = 10 },
      { letter = 'Í',     x = 159,     y = 419,     w = 15,      f = 10 },
      { letter = 'Î',     x = 173,     y = 419,     w = 12,      f = 10 },
      { letter = 'Ï',     x = 188,     y = 419,     w = 12,      f = 10 },
      { letter = 'Ò',     x = 202,     y = 419,     w = 12,      f = 12 },
      { letter = 'Ó',     x = 216,     y = 419,     w = 12,      f = 12 },
      { letter = 'Ô',     x = 230,     y = 419,     w = 13,      f = 12 },
      { letter = 'Õ',     x = 244,     y = 419,     w = 14,      f = 12 },
      { letter = 'Ù',     x = 259,     y = 419,     w = 14,      f = 13 },
      { letter = 'Ú',     x = 275,     y = 419,     w = 14,      f = 13 },
      { letter = 'Û',     x = 291,     y = 419,     w = 14,      f = 13 },
      { letter = 'Ü',     x = 307,     y = 419,     w = 14,      f = 13 },
    }
  }

  rval = resources_load_font('small_cursive_font', small_cursive_font)
  print("load font: " .. tostring(rval))

  local cursive_font = {
    key = "cursive_font",
    origin = { x = 0, y = 0 },
    texture = "gui",
    height = 20,
    spacing = 0,
    letters = {
      { letter = '!',     x = 4,       y = 55,     w = 1 },
      { letter = '"',     x = 6,       y = 55,     w = 3 },
      { letter = '#',     x = 10,      y = 55,     w = 5 },
      { letter = '$',     x = 17,      y = 55,     w = 5 },
      { letter = '%',     x = 24,      y = 55,     w = 9 },
      { letter = '&',     x = 34,      y = 55,     w = 8 },
      { letter = '\'',    x = 44,      y = 55,     w = 1 },
      { letter = '(',     x = 47,      y = 55,     w = 2 },
      { letter = ')',     x = 50,      y = 55,     w = 2 },
      { letter = '*',     x = 54,      y = 55,     w = 3 },
      { letter = '+',     x = 59,      y = 55,     w = 3 },
      { letter = ',',     x = 63,      y = 55,     w = 2 },
      { letter = '-',     x = 66,      y = 55,     w = 2 },
      { letter = '.',     x = 69,      y = 55,     w = 2 },
      { letter = '/',     x = 72,      y = 55,     w = 3 },
      { letter = '1',     x = 77,      y = 55,     w = 3 },
      { letter = '2',     x = 81,      y = 55,     w = 4 },
      { letter = '3',     x = 86,      y = 55,     w = 4 },
      { letter = '4',     x = 91,      y = 55,     w = 4 },
      { letter = '5',     x = 96,      y = 55,     w = 4 },
      { letter = '6',     x = 101,     y = 55,     w = 4 },
      { letter = '7',     x = 106,     y = 55,     w = 4 },
      { letter = '8',     x = 111,     y = 55,     w = 4 },
      { letter = '9',     x = 116,     y = 55,     w = 4 },
      { letter = '0',     x = 121,     y = 55,     w = 4 },
      { letter = ':',     x = 126,     y = 55,     w = 2 },
      { letter = ';',     x = 129,     y = 55,     w = 2 },
      { letter = '<',     x = 133,     y = 55,     w = 3 },
      { letter = '=',     x = 137,     y = 55,     w = 3 },
      { letter = '>',     x = 141,     y = 55,     w = 3 },
      { letter = '?',     x = 145,     y = 55,     w = 4 },
      { letter = '@',     x = 151,     y = 55,     w = 7 },

      { letter = 'A',     x = 0,         y = 240,     w = 16 },
      { letter = 'B',     x = 16*1,      y = 240,     w = 16 },
      { letter = 'C',     x = 16*2,      y = 240,     w = 16 },
      { letter = 'D',     x = 16*3,      y = 240,     w = 16 },
      { letter = 'E',     x = 16*4,      y = 240,     w = 16 },
      { letter = 'F',     x = 16*5,      y = 240,     w = 16 },
      { letter = 'G',     x = 16*6,      y = 240,     w = 16 },
      { letter = 'H',     x = 16*7,      y = 240,     w = 16 },
      { letter = 'I',     x = 16*8,      y = 240,     w = 16 },
      { letter = 'J',     x = 16*9,      y = 240,     w = 16 },
      { letter = 'K',     x = 16*10,     y = 240,     w = 16 },
      { letter = 'L',     x = 16*11,     y = 240,     w = 16 },
      { letter = 'M',     x = 16*12,     y = 240,     w = 16 },
      { letter = 'N',     x = 16*13,     y = 240,     w = 16 },
      { letter = 'O',     x = 16*14,     y = 240,     w = 16 },
      { letter = 'P',     x = 16*15,     y = 240,     w = 16 },
      { letter = 'Q',     x = 16*16,     y = 240,     w = 16 },
      { letter = 'R',     x = 16*17,     y = 240,     w = 16 },
      { letter = 'S',     x = 16*18,     y = 240,     w = 16 },
      { letter = 'T',     x = 16*19,     y = 240,     w = 16 },
      { letter = 'U',     x = 16*20,     y = 240,     w = 16 },
      { letter = 'V',     x = 16*21,     y = 240,     w = 16 },
      { letter = 'W',     x = 16*22,     y = 240,     w = 16 },
      { letter = 'X',     x = 16*23,     y = 240,     w = 16 },
      { letter = 'Y',     x = 16*24,     y = 240,     w = 16 },
      { letter = 'Z',     x = 16*25,     y = 240,     w = 16 },
      { letter = '[',     x = 214,     y = 71,     w = 2 },
      { letter = '\\',    x = 218,     y = 71,     w = 3 },
      { letter = ']',     x = 222,     y = 71,     w = 2 },
      { letter = '^',     x = 227,     y = 71,     w = 3 },
      { letter = '_',     x = 232,     y = 71,     w = 3 },
      { letter = '`',     x = 238,     y = 71,     w = 2 },

      { letter = 'a',     x = 2,       y = 211,     w = 9 },
      { letter = 'b',     x = 12,      y = 211,     w = 9 },
      { letter = 'c',     x = 21,      y = 211,     w = 8 },
      { letter = 'd',     x = 30,      y = 211,     w = 10 },
      { letter = 'e',     x = 40,      y = 211,     w = 9 },
      { letter = 'f',     x = 50,      y = 211,     w = 12 },
      { letter = 'g',     x = 63,      y = 211,     w = 11 },
      { letter = 'h',     x = 75,      y = 211,     w = 11 },
      { letter = 'i',     x = 87,      y = 211,     w = 5 },
      { letter = 'j',     x = 93,      y = 211,     w = 11 },
      { letter = 'k',     x = 105,     y = 211,     w = 10 },
      { letter = 'l',     x = 116,     y = 211,     w = 10 },
      { letter = 'm',     x = 128,     y = 211,     w = 12 },
      { letter = 'n',     x = 142,     y = 211,     w = 8 },
      { letter = 'o',     x = 152,     y = 211,     w = 9 },
      { letter = 'p',     x = 162,     y = 211,     w = 12 },
      { letter = 'q',     x = 176,     y = 211,     w = 10 },
      { letter = 'r',     x = 188,     y = 211,     w = 7 },
      { letter = 's',     x = 197,     y = 211,     w = 7 },
      { letter = 't',     x = 206,     y = 211,     w = 6 },
      { letter = 'u',     x = 213,     y = 211,     w = 9 },
      { letter = 'v',     x = 223,     y = 211,     w = 8 },
      { letter = 'w',     x = 233,     y = 211,     w = 11 },
      { letter = 'x',     x = 245,     y = 211,     w = 9 },
      { letter = 'y',     x = 256,     y = 211,     w = 11 },
      { letter = 'z',     x = 269,     y = 211,     w = 11 },
      { letter = '{',     x = 145,     y = 87,     w = 3 },
      { letter = '|',     x = 150,     y = 87,     w = 1 },
      { letter = '}',     x = 153,     y = 87,     w = 3 },
      { letter = '~',     x = 158,     y = 87,     w = 4 },
      { letter = ' ',     x = 164,     y = 87,     w = 2 },

      { letter = 'à',     x = 5,       y = 103,     w = 5 },
      { letter = 'á',     x = 11,      y = 103,     w = 5 },
      { letter = 'â',     x = 16,      y = 103,     w = 5 },
      { letter = 'ã',     x = 23,      y = 103,     w = 5 },
      { letter = 'ç',     x = 30,      y = 103,     w = 4 },
      { letter = 'ê',     x = 36,      y = 103,     w = 4 },
      { letter = 'è',     x = 41,      y = 103,     w = 4 },
      { letter = 'é',     x = 46,      y = 103,     w = 4 },
      { letter = 'ë',     x = 51,      y = 103,     w = 4 },
      { letter = 'ì',     x = 58,      y = 103,     w = 2 },
      { letter = 'í',     x = 63,      y = 103,     w = 2 },
      { letter = 'î',     x = 66,      y = 103,     w = 3 },
      { letter = 'ï',     x = 70,      y = 103,     w = 3 },
      { letter = 'ò',     x = 76,      y = 103,     w = 4 },
      { letter = 'ó',     x = 81,      y = 103,     w = 4 },
      { letter = 'ô',     x = 86,      y = 103,     w = 4 },
      { letter = 'õ',     x = 91,      y = 103,     w = 4 },
      { letter = 'ù',     x = 97,      y = 103,     w = 4 },
      { letter = 'ú',     x = 102,     y = 103,     w = 4 },
      { letter = 'û',     x = 107,     y = 103,     w = 4 },
      { letter = 'ü',     x = 112,     y = 103,     w = 4 },

      { letter = 'À',     x = 5,       y = 119,     w = 7 },
      { letter = 'Á',     x = 13,      y = 119,     w = 7 },
      { letter = 'Â',     x = 21,      y = 119,     w = 7 },
      { letter = 'Ã',     x = 29,      y = 119,     w = 7 },
      { letter = 'Ç',     x = 38,      y = 119,     w = 7 },
      { letter = 'Ê',     x = 47,      y = 119,     w = 6 },
      { letter = 'È',     x = 54,      y = 119,     w = 6 },
      { letter = 'É',     x = 61,      y = 119,     w = 6 },
      { letter = 'Ë',     x = 68,      y = 119,     w = 6 },
      { letter = 'Ì',     x = 76,      y = 119,     w = 2 },
      { letter = 'Í',     x = 81,      y = 119,     w = 2 },
      { letter = 'Î',     x = 84,      y = 119,     w = 3 },
      { letter = 'Ï',     x = 88,      y = 119,     w = 3 },
      { letter = 'Ò',     x = 93,      y = 119,     w = 7 },
      { letter = 'Ó',     x = 101,     y = 119,     w = 7 },
      { letter = 'Ô',     x = 109,     y = 119,     w = 7 },
      { letter = 'Õ',     x = 117,     y = 119,     w = 7 },
      { letter = 'Ù',     x = 126,     y = 119,     w = 7 },
      { letter = 'Ú',     x = 134,     y = 119,     w = 7 },
      { letter = 'Û',     x = 142,     y = 119,     w = 7 },
      { letter = 'Ü',     x = 150,     y = 119,     w = 7 },
    }
  }

  rval = resources_load_font('cursive_font', cursive_font)
  print("load font: " .. tostring(rval))


  return rval
end

return Resources
